### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasPassword' of null

### ISSUE THREAD

**Issue by skoniks** [h3imdall/ftp-remote-edit#323]
[Enter steps to reproduce:]

1. Open Plugin by hotkey

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.17.2

### Stack Trace

Uncaught TypeError: Cannot read property 'hasPassword' of null

```
At /Users/skoniks/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:479

TypeError: Cannot read property 'hasPassword' of null
    at FtpRemoteEdit.toggleFocus (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:479:18)
    at HTMLElement.ftpRemoteEditToggleFocus (/packages/ftp-remote-edit/lib/ftp-remote-edit.js:57:50)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:283942)
```

### Commands

```
  2x -0:06.9.0 ftp-remote-edit:toggle-focus (div.github-Git.is-empty)
```

### Non-Core Packages

```
ftp-remote-edit 0.17.2 
highlight-selected 0.16.0 
```

**Comment by userlond** [comment]
Are there any plans to merge fix into master? Extension doesn't work on my atom at all :(

**Comment by skoniks** [comment]
> Are there any plans to merge fix into master? Extension doesn't work on my atom at all :(

I fixed it by custom editing toggleFocus() function in ftp-remote-edit.js to
`  toggleFocus() {
      this.toggle();
  }
`
I understand that it`s a crutch, but it works :D

**Comment by skoniks** [comment]
> Are there any plans to merge fix into master? Extension doesn't work on my atom at all :(

Add self.init(); to /Users/user/.atom/packages/ftp-remote-edit/lib/ftp-remote-edit.js:478
Like in dev branch :D [here](https://github.com/h3imdall/ftp-remote-edit/commit/ecc34b2e1cc9633ad346a513d948ac27ea6a4f57)

**Comment by cschindl** [comment]
Sorry, that was my mistake. I forgot to release the changes.  Fixed in release [0.17.3](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.3). Thanks for the hint.

**Comment by umuthan** [comment]
I just updated the latest version 0.17.3 but i still see the same error.

<img width="1051" alt="Screen Shot 2019-08-29 at 20 41 11" src="https://user-images.githubusercontent.com/1632700/63963289-5ff3cc00-ca9d-11e9-8ef5-56796150b525.png">

**Comment by umuthan** [comment]
Sorry my atom is not the latest version. So i updated it then install ftp-remote-edit, now it is working.
