### ISSUE TITLE
Passwordless SSH leads to "All configured authentication methods failed"

### ISSUE THREAD

**Issue by caeyden** [h3imdall/ftp-remote-edit#379]
Connecting to an Ubuntu Server with passwordless SSH leads to the "All configured authentication methods failed" error. If setting Password Authentication back to 'yes' on the sshd_config file, the SFTP connection works. However, setting it to no does not, regardless of which 'Logon Type' is used.

**Comment by Cammy-the-block** [comment]
I have this same issue. I found a secure workaround. Ftp remote edit doesn't actually require the ability to login in with a password, it just needs password authentication to not be impossible. You can fool it by enabling password authentication on the server, but not actually allowing any users the ability to do so.

Edit your `/etc/ssh/sshd_config` to include

    Match User yourusername
    PasswordAuthentication no
    Match User All
    PasswordAuthentication yes

**Comment by caeyden** [comment]
Oh thanks for the suggestion! I set up the config file but still not having
luck in Atom.
When you use this, what authentication do you use in the server settings in
ftp remote edit?

**Comment by natsukashiiconsulting** [comment]
At the moment, regardless of what Logon Type I use in the FTP-Remote-Edit Server Settings, I still get the "All configured authentication methods failed" error

**Comment by bhakta0007** [comment]
What type of RSA key have you generated?

You will either find an RSA/DSA key or OpenSSH key.  The newer version of ssh-keygen (from OpenSSH) seems to generate the OpenSSH type keys.

tail -f ~/.ssh/id_rsa
-----END OPENSSH PRIVATE KEY-----
OR
-----END RSA PRIVATE KEY-----

When I ran into this problem, I ended up converting the OpenSSH style key to RSA using the command (Note: This will do an in-place change):

ssh-keygen -p  -m PEM -f ~/.ssh/id_rsa


[you don't need to do any change to the public key]

**Comment by AaronYoung5** [comment]
I fixed this error by running `ssh-add`. This adds the RSA/DSA files to your ssh agent. When I updated MacOS, I guess they were removed, so I re-ran this command which solved the issue.

**Comment by Javihache** [comment]
I had updated MacOS and probably got a similar to problem to @AaronYoung5, but I have run ssh-add and however the ssh agent still doesn't work for atom ftp-remote-edit... Tried restarting... nothing. I can try to remove completely FTP-Remote-Edit... but I am not sure if the problem is somewhere else. Any ideas?
